spring:
  messages:
    encoding: UTF-8
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/tiktok?useSSL=false&serverTimezone=GMT%2B8
    username: tiktok
    password: tiktok123456
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8080

mybatis-plus:
  type-aliases-package: com.tutou.tiktok.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
